// 到時候直接把資料填這裡面
// name, img_src = img/speakers/${name}.jpg
var speaker_list=["CZ",
"Abhishek Pitti",
"Darius Sit",
"Jason Jeon",
"Liu Gen Ping",
"Sam Bankman",
"Yoni Assia",
"Adrian Ang V-Ming",
"Darren Camas",
"Jasper",
"Loi Luu",
"Shaun Djie",
"Ameenah Gurib-Fakim",
"David Siemer",
"Jeff Garzik",
"Mai Fujimoto",
"Simon-OConnell",
"hsienhui-square",
"Andrew Quine",
"Dovey Wan",
"Jeff Paik",
"Manmeet Singh",
"Song Ye",
"jan liphardt",
"Andy Tai",
"Emily Parker",
"Jeremy Lam",
"Mario Larangeira",
"Source",
"john ng",
"Angie Lau",
"Emin Gün Sirer",
"Jim Radecki",
"Mary Saracco",
"Sunny Lu",
"nix nolledo",
"Anson-Zeall",
"Emma Liao",
"John Riggins",
"Matthew Roszak",
"Ted Lin",
"pablo_orlando 1",
"Anthony Pompliano",
"Eric van Miltenburg",
"Joshua Goldbard",
"Matthew Tan",
"Tiantian Kullander",
"pablo_orlando",
"Antony Lewis",
"Gin Chao",
"Jun Li",
"Michael Arrington",
"Tju Liang Chua",
"richmond teo",
"Chia Hock Lai ",
"Harry Halpin",
"Justin Sun",
"Michael Gu",
"Toby Simpson",
"sandeep nailwal",
"Da Hongfei",
"Helen Hai",
"Justin chow",
"Nicole Nyugen",
"Tory Reiss",
"sarah nabaa",
"Dan Whang",
"J P",
"Kenneth Oh",
"Ole Dubnov",
"Urszula McCormack",
"ulisse dell_orto",
"Daphne",
"Jack Liu",
"Kevin Teo",
"Patrick Dai",
"W. Scott Stornetta",
"周硕基",
"Daren Frankel",
"Jamie Burke",
"Kyle Samani",
"Patrick Yeo",
"YJ Kim"];
// 起始顯示的speaker數
var speaker_show_num=10;



// 現在先用假的資料
// for (var i = 0; i <18; i++) {
// 	speaker_list[i]=["Changpeng Zhao","Binance","CEO"];
// }

